<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::statement('SET FOREIGN_KEY_CHECKS=0;');
		DB::table('countries')->truncate();
		$countries = [
			[
				'code'             => 'AD',
				'name'             => 'Andorra',
				'tld'              => '.ad',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '376',
				'languages'        => 'ca',
			],
			[
				'code'             => 'AE',
				'name'             => 'al-Imārāt',
				'tld'              => '.ae',
				'continent_code'   => 'AS',
				'currency_code'    => 'AED',
				'int_calling_code' => '971',
				'languages'        => 'ar-AE,fa,en,hi,ur',
			],
			[
				'code'             => 'AF',
				'name'             => 'Afġānistān',
				'tld'              => '.af',
				'continent_code'   => 'AS',
				'currency_code'    => 'AFN',
				'int_calling_code' => '93',
				'languages'        => 'fa-AF,ps,uz-AF,tk',
			],
			[
				'code'             => 'AG',
				'name'             => 'Antigua and Barbuda',
				'tld'              => '.ag',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-268',
				'languages'        => 'en-AG',
			],
			[
				'code'             => 'AI',
				'name'             => 'Anguilla',
				'tld'              => '.ai',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-264',
				'languages'        => 'en-AI',
			],
			[
				'code'             => 'AL',
				'name'             => 'Shqipëria',
				'tld'              => '.al',
				'continent_code'   => 'EU',
				'currency_code'    => 'ALL',
				'int_calling_code' => '355',
				'languages'        => 'sq,el',
			],
			[
				'code'             => 'AM',
				'name'             => 'Hayastan',
				'tld'              => '.am',
				'continent_code'   => 'AS',
				'currency_code'    => 'AMD',
				'int_calling_code' => '374',
				'languages'        => 'hy',
			],
			[
				'code'             => 'AN',
				'name'             => 'Netherlands Antilles',
				'tld'              => '.an',
				'continent_code'   => 'NA',
				'currency_code'    => 'ANG',
				'int_calling_code' => '599',
				'languages'        => 'nl-AN,en,es',
			],
			[
				'code'             => 'AO',
				'name'             => 'Angola',
				'tld'              => '.ao',
				'continent_code'   => 'AF',
				'currency_code'    => 'AOA',
				'int_calling_code' => '244',
				'languages'        => 'pt-AO',
			],
			[
				'code'             => 'AQ',
				'name'             => 'Antarctica',
				'tld'              => '.aq',
				'continent_code'   => 'AN',
				'currency_code'    => '',
				'int_calling_code' => '',
				'languages'        => '',
			],
			[
				'code'             => 'AR',
				'name'             => 'Argentina',
				'tld'              => '.ar',
				'continent_code'   => 'SA',
				'currency_code'    => 'ARS',
				'int_calling_code' => '54',
				'languages'        => 'es-AR,en,it,de,fr,gn',
			],
			[
				'code'             => 'AS',
				'name'             => 'American Samoa',
				'tld'              => '.as',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-684',
				'languages'        => 'en-AS,sm,to',
			],
			[
				'code'             => 'AT',
				'name'             => 'Österreich',
				'tld'              => '.at',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '43',
				'languages'        => 'de-AT,hr,hu,sl',
			],
			[
				'code'             => 'AU',
				'name'             => 'Australia',
				'tld'              => '.au',
				'continent_code'   => 'OC',
				'currency_code'    => 'AUD',
				'int_calling_code' => '61',
				'languages'        => 'en-AU',
			],
			[
				'code'             => 'AW',
				'name'             => 'Aruba',
				'tld'              => '.aw',
				'continent_code'   => 'NA',
				'currency_code'    => 'AWG',
				'int_calling_code' => '297',
				'languages'        => 'nl-AW,es,en',
			],
			[
				'code'             => 'AX',
				'name'             => 'Aland Islands',
				'tld'              => '.ax',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '+358-18',
				'languages'        => 'sv-AX',
			],
			[
				'code'             => 'AZ',
				'name'             => 'Azərbaycan',
				'tld'              => '.az',
				'continent_code'   => 'AS',
				'currency_code'    => 'AZN',
				'int_calling_code' => '994',
				'languages'        => 'az,ru,hy',
			],
			[
				'code'             => 'BA',
				'name'             => 'Bosna i Hercegovina',
				'tld'              => '.ba',
				'continent_code'   => 'EU',
				'currency_code'    => 'BAM',
				'int_calling_code' => '387',
				'languages'        => 'bs,hr-BA,sr-BA',
			],
			[
				'code'             => 'BB',
				'name'             => 'Barbados',
				'tld'              => '.bb',
				'continent_code'   => 'NA',
				'currency_code'    => 'BBD',
				'int_calling_code' => '+1-246',
				'languages'        => 'en-BB',
			],
			[
				'code'             => 'BD',
				'name'             => 'Bāṅlādēś',
				'tld'              => '.bd',
				'continent_code'   => 'AS',
				'currency_code'    => 'BDT',
				'int_calling_code' => '880',
				'languages'        => 'bn-BD,en',
			],
			[
				'code'             => 'BE',
				'name'             => 'Belgique',
				'tld'              => '.be',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '32',
				'languages'        => 'nl-BE,fr-BE,de-BE',
			],
			[
				'code'             => 'BF',
				'name'             => 'Burkina Faso',
				'tld'              => '.bf',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '226',
				'languages'        => 'fr-BF',
			],
			[
				'code'             => 'BG',
				'name'             => 'Bŭlgarija',
				'tld'              => '.bg',
				'continent_code'   => 'EU',
				'currency_code'    => 'BGN',
				'int_calling_code' => '359',
				'languages'        => 'bg,tr-BG,rom',
			],
			[
				'code'             => 'BH',
				'name'             => 'al-Baḥrayn',
				'tld'              => '.bh',
				'continent_code'   => 'AS',
				'currency_code'    => 'BHD',
				'int_calling_code' => '973',
				'languages'        => 'ar-BH,en,fa,ur',
			],
			[
				'code'             => 'BI',
				'name'             => 'Burundi',
				'tld'              => '.bi',
				'continent_code'   => 'AF',
				'currency_code'    => 'BIF',
				'int_calling_code' => '257',
				'languages'        => 'fr-BI,rn',
			],
			[
				'code'             => 'BJ',
				'name'             => 'Bénin',
				'tld'              => '.bj',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '+229',
				'languages'        => 'fr-BJ',
			],
			[
				'code'             => 'BL',
				'name'             => 'Saint Barthelemy',
				'tld'              => '.gp',
				'continent_code'   => 'NA',
				'currency_code'    => 'EUR',
				'int_calling_code' => '590',
				'languages'        => 'fr',
			],
			[
				'code'             => 'BM',
				'name'             => 'Bermuda',
				'tld'              => '.bm',
				'continent_code'   => 'NA',
				'currency_code'    => 'BMD',
				'int_calling_code' => '+1-441',
				'languages'        => 'en-BM,pt',
			],
			[
				'code'             => 'BN',
				'name'             => 'Brunei Darussalam',
				'tld'              => '.bn',
				'continent_code'   => 'AS',
				'currency_code'    => 'BND',
				'int_calling_code' => '673',
				'languages'        => 'ms-BN,en-BN',
			],
			[
				'code'             => 'BO',
				'name'             => 'Bolivia',
				'tld'              => '.bo',
				'continent_code'   => 'SA',
				'currency_code'    => 'BOB',
				'int_calling_code' => '591',
				'languages'        => 'es-BO,qu,ay',
			],
			[
				'code'             => 'BQ',
				'name'             => 'Bonaire, Saint Eustatius and Saba ',
				'tld'              => '.bq',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '599',
				'languages'        => 'nl,pap,en',
			],
			[
				'code'             => 'BR',
				'name'             => 'Brasil',
				'tld'              => '.br',
				'continent_code'   => 'SA',
				'currency_code'    => 'BRL',
				'int_calling_code' => '55',
				'languages'        => 'pt-BR,es,en,fr',
			],
			[
				'code'             => 'BS',
				'name'             => 'Bahamas',
				'tld'              => '.bs',
				'continent_code'   => 'NA',
				'currency_code'    => 'BSD',
				'int_calling_code' => '+1-242',
				'languages'        => 'en-BS',
			],
			[
				'code'             => 'BT',
				'name'             => 'Druk-yul',
				'tld'              => '.bt',
				'continent_code'   => 'AS',
				'currency_code'    => 'BTN',
				'int_calling_code' => '975',
				'languages'        => 'dz',
			],
			[
				'code'             => 'BV',
				'name'             => 'Bouvet Island',
				'tld'              => '.bv',
				'continent_code'   => 'AN',
				'currency_code'    => 'NOK',
				'int_calling_code' => '',
				'languages'        => '',
			],
			[
				'code'             => 'BW',
				'name'             => 'Botswana',
				'tld'              => '.bw',
				'continent_code'   => 'AF',
				'currency_code'    => 'BWP',
				'int_calling_code' => '267',
				'languages'        => 'en-BW,tn-BW',
			],
			[
				'code'             => 'BY',
				'name'             => 'Biełaruś',
				'tld'              => '.by',
				'continent_code'   => 'EU',
				'currency_code'    => 'BYR',
				'int_calling_code' => '375',
				'languages'        => 'be,ru',
			],
			[
				'code'             => 'BZ',
				'name'             => 'Belize',
				'tld'              => '.bz',
				'continent_code'   => 'NA',
				'currency_code'    => 'BZD',
				'int_calling_code' => '501',
				'languages'        => 'en-BZ,es',
			],
			[
				'code'             => 'CA',
				'name'             => 'Canada',
				'tld'              => '.ca',
				'continent_code'   => 'NA',
				'currency_code'    => 'CAD',
				'int_calling_code' => '1',
				'languages'        => 'en-CA,fr-CA,iu',
			],
			[
				'code'             => 'CC',
				'name'             => 'Cocos Islands',
				'tld'              => '.cc',
				'continent_code'   => 'AS',
				'currency_code'    => 'AUD',
				'int_calling_code' => '61',
				'languages'        => 'ms-CC,en',
			],
			[
				'code'             => 'CD',
				'name'             => 'RDC',
				'tld'              => '.cd',
				'continent_code'   => 'AF',
				'currency_code'    => 'CDF',
				'int_calling_code' => '243',
				'languages'        => 'fr-CD,ln,kg',
			],
			[
				'code'             => 'CF',
				'name'             => 'Centrafrique',
				'tld'              => '.cf',
				'continent_code'   => 'AF',
				'currency_code'    => 'XAF',
				'int_calling_code' => '236',
				'languages'        => 'fr-CF,sg,ln,kg',
			],
			[
				'code'             => 'CG',
				'name'             => 'Congo',
				'tld'              => '.cg',
				'continent_code'   => 'AF',
				'currency_code'    => 'XAF',
				'int_calling_code' => '242',
				'languages'        => 'fr-CG,kg,ln-CG',
			],
			[
				'code'             => 'CH',
				'name'             => 'Switzerland',
				'tld'              => '.ch',
				'continent_code'   => 'EU',
				'currency_code'    => 'CHF',
				'int_calling_code' => '41',
				'languages'        => 'de-CH,fr-CH,it-CH,rm',
			],
			[
				'code'             => 'CI',
				'name'             => 'Côte d\'Ivoire',
				'tld'              => '.ci',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '225',
				'languages'        => 'fr-CI',
			],
			[
				'code'             => 'CK',
				'name'             => 'Cook Islands',
				'tld'              => '.ck',
				'continent_code'   => 'OC',
				'currency_code'    => 'NZD',
				'int_calling_code' => '682',
				'languages'        => 'en-CK,mi',
			],
			[
				'code'             => 'CL',
				'name'             => 'Chile',
				'tld'              => '.cl',
				'continent_code'   => 'SA',
				'currency_code'    => 'CLP',
				'int_calling_code' => '56',
				'languages'        => 'es-CL',
			],
			[
				'code'             => 'CM',
				'name'             => 'Cameroun',
				'tld'              => '.cm',
				'continent_code'   => 'AF',
				'currency_code'    => 'XAF',
				'int_calling_code' => '237',
				'languages'        => 'fr-CM,en-CM',
			],
			[
				'code'             => 'CN',
				'name'             => 'Zhōngguó',
				'tld'              => '.cn',
				'continent_code'   => 'AS',
				'currency_code'    => 'CNY',
				'int_calling_code' => '86',
				'languages'        => 'zh-CN,yue,wuu,dta,ug,za',
			],
			[
				'code'             => 'CO',
				'name'             => 'Colombia',
				'tld'              => '.co',
				'continent_code'   => 'SA',
				'currency_code'    => 'COP',
				'int_calling_code' => '57',
				'languages'        => 'es-CO',
			],
			[
				'code'             => 'CR',
				'name'             => 'Costa Rica',
				'tld'              => '.cr',
				'continent_code'   => 'NA',
				'currency_code'    => 'CRC',
				'int_calling_code' => '506',
				'languages'        => 'es-CR,en',
			],
			[
				'code'             => 'CS',
				'name'             => 'Serbia and Montenegro',
				'tld'              => '.cs',
				'continent_code'   => 'EU',
				'currency_code'    => 'RSD',
				'int_calling_code' => '381',
				'languages'        => 'cu,hu,sq,sr',
			],
			[
				'code'             => 'CU',
				'name'             => 'Cuba',
				'tld'              => '.cu',
				'continent_code'   => 'NA',
				'currency_code'    => 'CUP',
				'int_calling_code' => '53',
				'languages'        => 'es-CU',
			],
			[
				'code'             => 'CV',
				'name'             => 'Cabo Verde',
				'tld'              => '.cv',
				'continent_code'   => 'AF',
				'currency_code'    => 'CVE',
				'int_calling_code' => '238',
				'languages'        => 'pt-CV',
			],
			[
				'code'             => 'CW',
				'name'             => 'Curacao',
				'tld'              => '.cw',
				'continent_code'   => 'NA',
				'currency_code'    => 'ANG',
				'int_calling_code' => '599',
				'languages'        => 'nl,pap',
			],
			[
				'code'             => 'CX',
				'name'             => 'Christmas Island',
				'tld'              => '.cx',
				'continent_code'   => 'AS',
				'currency_code'    => 'AUD',
				'int_calling_code' => '61',
				'languages'        => 'en,zh,ms-CC',
			],
			[
				'code'             => 'CY',
				'name'             => 'Kýpros (Kıbrıs)',
				'tld'              => '.cy',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '357',
				'languages'        => 'el-CY,tr-CY,en',
			],
			[
				'code'             => 'CZ',
				'name'             => 'Česko',
				'tld'              => '.cz',
				'continent_code'   => 'EU',
				'currency_code'    => 'CZK',
				'int_calling_code' => '420',
				'languages'        => 'cs,sk',
			],
			[
				'code'             => 'DE',
				'name'             => 'Deutschland',
				'tld'              => '.de',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '49',
				'languages'        => 'de',
			],
			[
				'code'             => 'DJ',
				'name'             => 'Djibouti',
				'tld'              => '.dj',
				'continent_code'   => 'AF',
				'currency_code'    => 'DJF',
				'int_calling_code' => '253',
				'languages'        => 'fr-DJ,ar,so-DJ,aa',
			],
			[
				'code'             => 'DK',
				'name'             => 'Danmark',
				'tld'              => '.dk',
				'continent_code'   => 'EU',
				'currency_code'    => 'DKK',
				'int_calling_code' => '45',
				'languages'        => 'da-DK,en,fo,de-DK',
			],
			[
				'code'             => 'DM',
				'name'             => 'Dominica',
				'tld'              => '.dm',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-767',
				'languages'        => 'en-DM',
			],
			[
				'code'             => 'DO',
				'name'             => 'República Dominicana',
				'tld'              => '.do',
				'continent_code'   => 'NA',
				'currency_code'    => 'DOP',
				'int_calling_code' => '+809/829/849',
				'languages'        => 'es-DO',
			],
			[
				'code'             => 'DZ',
				'name'             => 'Algérie',
				'tld'              => '.dz',
				'continent_code'   => 'AF',
				'currency_code'    => 'DZD',
				'int_calling_code' => '213',
				'languages'        => 'ar-DZ,fr',
			],
			[
				'code'             => 'EC',
				'name'             => 'Ecuador',
				'tld'              => '.ec',
				'continent_code'   => 'SA',
				'currency_code'    => 'USD',
				'int_calling_code' => '593',
				'languages'        => 'es-EC',
			],
			[
				'code'             => 'EE',
				'name'             => 'Eesti',
				'tld'              => '.ee',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '372',
				'languages'        => 'et,ru',
			],
			[
				'code'             => 'EG',
				'name'             => 'Egypt',
				'tld'              => '.eg',
				'continent_code'   => 'AF',
				'currency_code'    => 'EGP',
				'int_calling_code' => '20',
				'languages'        => 'ar-EG,en,fr',
			],
			[
				'code'             => 'EH',
				'name'             => 'aṣ-Ṣaḥrāwīyâ al-ʿArabīyâ',
				'tld'              => '.eh',
				'continent_code'   => 'AF',
				'currency_code'    => 'MAD',
				'int_calling_code' => '212',
				'languages'        => 'ar,mey',
			],
			[
				'code'             => 'ER',
				'name'             => 'Ertrā',
				'tld'              => '.er',
				'continent_code'   => 'AF',
				'currency_code'    => 'ERN',
				'int_calling_code' => '291',
				'languages'        => 'aa-ER,ar,tig,kun,ti-ER',
			],
			[
				'code'             => 'ES',
				'name'             => 'España',
				'tld'              => '.es',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '34',
				'languages'        => 'es-ES,ca,gl,eu,oc',
			],
			[
				'code'             => 'ET',
				'name'             => 'Ityoṗya',
				'tld'              => '.et',
				'continent_code'   => 'AF',
				'currency_code'    => 'ETB',
				'int_calling_code' => '251',
				'languages'        => 'am,en-ET,om-ET,ti-ET,so-ET,sid',
			],
			[
				'code'             => 'FI',
				'name'             => 'Suomi (Finland)',
				'tld'              => '.fi',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '358',
				'languages'        => 'fi-FI,sv-FI,smn',
			],
			[
				'code'             => 'FJ',
				'name'             => 'Viti',
				'tld'              => '.fj',
				'continent_code'   => 'OC',
				'currency_code'    => 'FJD',
				'int_calling_code' => '679',
				'languages'        => 'en-FJ,fj',
			],
			[
				'code'             => 'FK',
				'name'             => 'Falkland Islands',
				'tld'              => '.fk',
				'continent_code'   => 'SA',
				'currency_code'    => 'FKP',
				'int_calling_code' => '500',
				'languages'        => 'en-FK',
			],
			[
				'code'             => 'FM',
				'name'             => 'Micronesia',
				'tld'              => '.fm',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '691',
				'languages'        => 'en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg',
			],
			[
				'code'             => 'FO',
				'name'             => 'Føroyar',
				'tld'              => '.fo',
				'continent_code'   => 'EU',
				'currency_code'    => 'DKK',
				'int_calling_code' => '298',
				'languages'        => 'fo,da-FO',
			],
			[
				'code'             => 'FR',
				'name'             => 'France',
				'tld'              => '.fr',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '33',
				'languages'        => 'fr-FR,frp,br,co,ca,eu,oc',
			],
			[
				'code'             => 'GA',
				'name'             => 'Gabon',
				'tld'              => '.ga',
				'continent_code'   => 'AF',
				'currency_code'    => 'XAF',
				'int_calling_code' => '241',
				'languages'        => 'fr-GA',
			],
			[
				'code'             => 'GD',
				'name'             => 'Grenada',
				'tld'              => '.gd',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-473',
				'languages'        => 'en-GD',
			],
			[
				'code'             => 'GE',
				'name'             => 'Sak\'art\'velo',
				'tld'              => '.ge',
				'continent_code'   => 'AS',
				'currency_code'    => 'GEL',
				'int_calling_code' => '995',
				'languages'        => 'ka,ru,hy,az',
			],
			[
				'code'             => 'GF',
				'name'             => 'Guyane',
				'tld'              => '.gf',
				'continent_code'   => 'SA',
				'currency_code'    => 'EUR',
				'int_calling_code' => '594',
				'languages'        => 'fr-GF',
			],
			[
				'code'             => 'GG',
				'name'             => 'Guernsey',
				'tld'              => '.gg',
				'continent_code'   => 'EU',
				'currency_code'    => 'GBP',
				'int_calling_code' => '+44-1481',
				'languages'        => 'en,fr',
			],
			[
				'code'             => 'GH',
				'name'             => 'Ghana',
				'tld'              => '.gh',
				'continent_code'   => 'AF',
				'currency_code'    => 'GHS',
				'int_calling_code' => '233',
				'languages'        => 'en-GH,ak,ee,tw',
			],
			[
				'code'             => 'GI',
				'name'             => 'Gibraltar',
				'tld'              => '.gi',
				'continent_code'   => 'EU',
				'currency_code'    => 'GIP',
				'int_calling_code' => '350',
				'languages'        => 'en-GI,es,it,pt',
			],
			[
				'code'             => 'GL',
				'name'             => 'Grønland',
				'tld'              => '.gl',
				'continent_code'   => 'NA',
				'currency_code'    => 'DKK',
				'int_calling_code' => '299',
				'languages'        => 'kl,da-GL,en',
			],
			[
				'code'             => 'GM',
				'name'             => 'Gambia',
				'tld'              => '.gm',
				'continent_code'   => 'AF',
				'currency_code'    => 'GMD',
				'int_calling_code' => '220',
				'languages'        => 'en-GM,mnk,wof,wo,ff',
			],
			[
				'code'             => 'GN',
				'name'             => 'Guinée',
				'tld'              => '.gn',
				'continent_code'   => 'AF',
				'currency_code'    => 'GNF',
				'int_calling_code' => '224',
				'languages'        => 'fr-GN',
			],
			[
				'code'             => 'GP',
				'name'             => 'Guadeloupe',
				'tld'              => '.gp',
				'continent_code'   => 'NA',
				'currency_code'    => 'EUR',
				'int_calling_code' => '590',
				'languages'        => 'fr-GP',
			],
			[
				'code'             => 'GQ',
				'name'             => 'Guinée Equatoriale',
				'tld'              => '.gq',
				'continent_code'   => 'AF',
				'currency_code'    => 'XAF',
				'int_calling_code' => '240',
				'languages'        => 'es-GQ,fr',
			],
			[
				'code'             => 'GR',
				'name'             => 'Elláda',
				'tld'              => '.gr',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '30',
				'languages'        => 'el-GR,en,fr',
			],
			[
				'code'             => 'GS',
				'name'             => 'South Georgia and the South Sandwich Islands',
				'tld'              => '.gs',
				'continent_code'   => 'AN',
				'currency_code'    => 'GBP',
				'int_calling_code' => '',
				'languages'        => 'en',
			],
			[
				'code'             => 'GT',
				'name'             => 'Guatemala',
				'tld'              => '.gt',
				'continent_code'   => 'NA',
				'currency_code'    => 'GTQ',
				'int_calling_code' => '502',
				'languages'        => 'es-GT',
			],
			[
				'code'             => 'GU',
				'name'             => 'Guam',
				'tld'              => '.gu',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-671',
				'languages'        => 'en-GU,ch-GU',
			],
			[
				'code'             => 'GW',
				'name'             => 'Guiné-Bissau',
				'tld'              => '.gw',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '245',
				'languages'        => 'pt-GW,pov',
			],
			[
				'code'             => 'GY',
				'name'             => 'Guyana',
				'tld'              => '.gy',
				'continent_code'   => 'SA',
				'currency_code'    => 'GYD',
				'int_calling_code' => '592',
				'languages'        => 'en-GY',
			],
			[
				'code'             => 'HK',
				'name'             => 'Hèunggóng',
				'tld'              => '.hk',
				'continent_code'   => 'AS',
				'currency_code'    => 'HKD',
				'int_calling_code' => '852',
				'languages'        => 'zh-HK,yue,zh,en',
			],
			[
				'code'             => 'HM',
				'name'             => 'Heard Island and McDonald Islands',
				'tld'              => '.hm',
				'continent_code'   => 'AN',
				'currency_code'    => 'AUD',
				'int_calling_code' => ' ',
				'languages'        => '',
			],
			[
				'code'             => 'HN',
				'name'             => 'Honduras',
				'tld'              => '.hn',
				'continent_code'   => 'NA',
				'currency_code'    => 'HNL',
				'int_calling_code' => '504',
				'languages'        => 'es-HN',
			],
			[
				'code'             => 'HR',
				'name'             => 'Hrvatska',
				'tld'              => '.hr',
				'continent_code'   => 'EU',
				'currency_code'    => 'HRK',
				'int_calling_code' => '385',
				'languages'        => 'hr-HR,sr',
			],
			[
				'code'             => 'HT',
				'name'             => 'Haïti',
				'tld'              => '.ht',
				'continent_code'   => 'NA',
				'currency_code'    => 'HTG',
				'int_calling_code' => '509',
				'languages'        => 'ht,fr-HT',
			],
			[
				'code'             => 'HU',
				'name'             => 'Magyarország',
				'tld'              => '.hu',
				'continent_code'   => 'EU',
				'currency_code'    => 'HUF',
				'int_calling_code' => '36',
				'languages'        => 'hu-HU',
			],
			[
				'code'             => 'ID',
				'name'             => 'Indonesia',
				'tld'              => '.id',
				'continent_code'   => 'AS',
				'currency_code'    => 'IDR',
				'int_calling_code' => '62',
				'languages'        => 'id,en,nl,jv',
			],
			[
				'code'             => 'IE',
				'name'             => 'Ireland',
				'tld'              => '.ie',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '353',
				'languages'        => 'en-IE,ga-IE',
			],
			[
				'code'             => 'IL',
				'name'             => 'Yiśrā\'ēl',
				'tld'              => '.il',
				'continent_code'   => 'AS',
				'currency_code'    => 'ILS',
				'int_calling_code' => '972',
				'languages'        => 'he,ar-IL,en-IL,',
			],
			[
				'code'             => 'IM',
				'name'             => 'Isle of Man',
				'tld'              => '.im',
				'continent_code'   => 'EU',
				'currency_code'    => 'GBP',
				'int_calling_code' => '+44-1624',
				'languages'        => 'en,gv',
			],
			[
				'code'             => 'IN',
				'name'             => 'Bhārat',
				'tld'              => '.in',
				'continent_code'   => 'AS',
				'currency_code'    => 'INR',
				'int_calling_code' => '91',
				'languages'        => 'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,k',
			],
			[
				'code'             => 'IO',
				'name'             => 'British Indian Ocean Territory',
				'tld'              => '.io',
				'continent_code'   => 'AS',
				'currency_code'    => 'USD',
				'int_calling_code' => '246',
				'languages'        => 'en-IO',
			],
			[
				'code'             => 'IQ',
				'name'             => 'al-ʿIrāq',
				'tld'              => '.iq',
				'continent_code'   => 'AS',
				'currency_code'    => 'IQD',
				'int_calling_code' => '964',
				'languages'        => 'ar-IQ,ku,hy',
			],
			[
				'code'             => 'IR',
				'name'             => 'Īrān',
				'tld'              => '.ir',
				'continent_code'   => 'AS',
				'currency_code'    => 'IRR',
				'int_calling_code' => '98',
				'languages'        => 'fa-IR,ku',
			],
			[
				'code'             => 'IS',
				'name'             => 'Ísland',
				'tld'              => '.is',
				'continent_code'   => 'EU',
				'currency_code'    => 'ISK',
				'int_calling_code' => '354',
				'languages'        => 'is,en,de,da,sv,no',
			],
			[
				'code'             => 'IT',
				'name'             => 'Italia',
				'tld'              => '.it',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '39',
				'languages'        => 'it-IT,en,de-IT,fr-IT,sc,ca,co,sl',
			],
			[
				'code'             => 'JE',
				'name'             => 'Jersey',
				'tld'              => '.je',
				'continent_code'   => 'EU',
				'currency_code'    => 'GBP',
				'int_calling_code' => '+44-1534',
				'languages'        => 'en,pt',
			],
			[
				'code'             => 'JM',
				'name'             => 'Jamaica',
				'tld'              => '.jm',
				'continent_code'   => 'NA',
				'currency_code'    => 'JMD',
				'int_calling_code' => '+1-876',
				'languages'        => 'en-JM',
			],
			[
				'code'             => 'JO',
				'name'             => 'al-Urdun',
				'tld'              => '.jo',
				'continent_code'   => 'AS',
				'currency_code'    => 'JOD',
				'int_calling_code' => '962',
				'languages'        => 'ar-JO,en',
			],
			[
				'code'             => 'JP',
				'name'             => 'Nihon',
				'tld'              => '.jp',
				'continent_code'   => 'AS',
				'currency_code'    => 'JPY',
				'int_calling_code' => '81',
				'languages'        => 'ja',
			],
			[
				'code'             => 'KE',
				'name'             => 'Kenya',
				'tld'              => '.ke',
				'continent_code'   => 'AF',
				'currency_code'    => 'KES',
				'int_calling_code' => '254',
				'languages'        => 'en-KE,sw-KE',
			],
			[
				'code'             => 'KG',
				'name'             => 'Kyrgyzstan',
				'tld'              => '.kg',
				'continent_code'   => 'AS',
				'currency_code'    => 'KGS',
				'int_calling_code' => '996',
				'languages'        => 'ky,uz,ru',
			],
			[
				'code'             => 'KH',
				'name'             => 'Kambucā',
				'tld'              => '.kh',
				'continent_code'   => 'AS',
				'currency_code'    => 'KHR',
				'int_calling_code' => '855',
				'languages'        => 'km,fr,en',
			],
			[
				'code'             => 'KI',
				'name'             => 'Kiribati',
				'tld'              => '.ki',
				'continent_code'   => 'OC',
				'currency_code'    => 'AUD',
				'int_calling_code' => '686',
				'languages'        => 'en-KI,gil',
			],
			[
				'code'             => 'KM',
				'name'             => 'Comores',
				'tld'              => '.km',
				'continent_code'   => 'AF',
				'currency_code'    => 'KMF',
				'int_calling_code' => '269',
				'languages'        => 'ar,fr-KM',
			],
			[
				'code'             => 'KN',
				'name'             => 'Saint Kitts and Nevis',
				'tld'              => '.kn',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-869',
				'languages'        => 'en-KN',
			],
			[
				'code'             => 'KP',
				'name'             => 'Joseon',
				'tld'              => '.kp',
				'continent_code'   => 'AS',
				'currency_code'    => 'KPW',
				'int_calling_code' => '850',
				'languages'        => 'ko-KP',
			],
			[
				'code'             => 'KR',
				'name'             => 'Hanguk',
				'tld'              => '.kr',
				'continent_code'   => 'AS',
				'currency_code'    => 'KRW',
				'int_calling_code' => '82',
				'languages'        => 'ko-KR,en',
			],
			[
				'code'             => 'KW',
				'name'             => 'al-Kuwayt',
				'tld'              => '.kw',
				'continent_code'   => 'AS',
				'currency_code'    => 'KWD',
				'int_calling_code' => '965',
				'languages'        => 'ar-KW,en',
			],
			[
				'code'             => 'KY',
				'name'             => 'Cayman Islands',
				'tld'              => '.ky',
				'continent_code'   => 'NA',
				'currency_code'    => 'KYD',
				'int_calling_code' => '+1-345',
				'languages'        => 'en-KY',
			],
			[
				'code'             => 'KZ',
				'name'             => 'Ķazaķstan',
				'tld'              => '.kz',
				'continent_code'   => 'AS',
				'currency_code'    => 'KZT',
				'int_calling_code' => '7',
				'languages'        => 'kk,ru',
			],
			[
				'code'             => 'LA',
				'name'             => 'Lāw',
				'tld'              => '.la',
				'continent_code'   => 'AS',
				'currency_code'    => 'LAK',
				'int_calling_code' => '856',
				'languages'        => 'lo,fr,en',
			],
			[
				'code'             => 'LB',
				'name'             => 'Lubnān',
				'tld'              => '.lb',
				'continent_code'   => 'AS',
				'currency_code'    => 'LBP',
				'int_calling_code' => '961',
				'languages'        => 'ar-LB,fr-LB,en,hy',
			],
			[
				'code'             => 'LC',
				'name'             => 'Saint Lucia',
				'tld'              => '.lc',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-758',
				'languages'        => 'en-LC',
			],
			[
				'code'             => 'LI',
				'name'             => 'Liechtenstein',
				'tld'              => '.li',
				'continent_code'   => 'EU',
				'currency_code'    => 'CHF',
				'int_calling_code' => '423',
				'languages'        => 'de-LI',
			],
			[
				'code'             => 'LK',
				'name'             => 'Šrī Laṁkā',
				'tld'              => '.lk',
				'continent_code'   => 'AS',
				'currency_code'    => 'LKR',
				'int_calling_code' => '94',
				'languages'        => 'si,ta,en',
			],
			[
				'code'             => 'LR',
				'name'             => 'Liberia',
				'tld'              => '.lr',
				'continent_code'   => 'AF',
				'currency_code'    => 'LRD',
				'int_calling_code' => '231',
				'languages'        => 'en-LR',
			],
			[
				'code'             => 'LS',
				'name'             => 'Lesotho',
				'tld'              => '.ls',
				'continent_code'   => 'AF',
				'currency_code'    => 'LSL',
				'int_calling_code' => '266',
				'languages'        => 'en-LS,st,zu,xh',
			],
			[
				'code'             => 'LT',
				'name'             => 'Lietuva',
				'tld'              => '.lt',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '370',
				'languages'        => 'lt,ru,pl',
			],
			[
				'code'             => 'LU',
				'name'             => 'Lëtzebuerg',
				'tld'              => '.lu',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '352',
				'languages'        => 'lb,de-LU,fr-LU',
			],
			[
				'code'             => 'LV',
				'name'             => 'Latvija',
				'tld'              => '.lv',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '371',
				'languages'        => 'lv,ru,lt',
			],
			[
				'code'             => 'LY',
				'name'             => 'Lībiyā',
				'tld'              => '.ly',
				'continent_code'   => 'AF',
				'currency_code'    => 'LYD',
				'int_calling_code' => '218',
				'languages'        => 'ar-LY,it,en',
			],
			[
				'code'             => 'MA',
				'name'             => 'Maroc',
				'tld'              => '.ma',
				'continent_code'   => 'AF',
				'currency_code'    => 'MAD',
				'int_calling_code' => '212',
				'languages'        => 'ar-MA,fr',
			],
			[
				'code'             => 'MC',
				'name'             => 'Monaco',
				'tld'              => '.mc',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '377',
				'languages'        => 'fr-MC,en,it',
			],
			[
				'code'             => 'MD',
				'name'             => 'Moldova',
				'tld'              => '.md',
				'continent_code'   => 'EU',
				'currency_code'    => 'MDL',
				'int_calling_code' => '373',
				'languages'        => 'ro,ru,gag,tr',
			],
			[
				'code'             => 'ME',
				'name'             => 'Crna Gora',
				'tld'              => '.me',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '382',
				'languages'        => 'sr,hu,bs,sq,hr,rom',
			],
			[
				'code'             => 'MF',
				'name'             => 'Saint Martin',
				'tld'              => '.gp',
				'continent_code'   => 'NA',
				'currency_code'    => 'EUR',
				'int_calling_code' => '590',
				'languages'        => 'fr',
			],
			[
				'code'             => 'MG',
				'name'             => 'Madagascar',
				'tld'              => '.mg',
				'continent_code'   => 'AF',
				'currency_code'    => 'MGA',
				'int_calling_code' => '261',
				'languages'        => 'fr-MG,mg',
			],
			[
				'code'             => 'MH',
				'name'             => 'Marshall Islands',
				'tld'              => '.mh',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '692',
				'languages'        => 'mh,en-MH',
			],
			[
				'code'             => 'MK',
				'name'             => 'Makedonija',
				'tld'              => '.mk',
				'continent_code'   => 'EU',
				'currency_code'    => 'MKD',
				'int_calling_code' => '389',
				'languages'        => 'mk,sq,tr,rmm,sr',
			],
			[
				'code'             => 'ML',
				'name'             => 'Mali',
				'tld'              => '.ml',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '223',
				'languages'        => 'fr-ML,bm',
			],
			[
				'code'             => 'MM',
				'name'             => 'Mẏanmā',
				'tld'              => '.mm',
				'continent_code'   => 'AS',
				'currency_code'    => 'MMK',
				'int_calling_code' => '95',
				'languages'        => 'my',
			],
			[
				'code'             => 'MN',
				'name'             => 'Mongol Uls',
				'tld'              => '.mn',
				'continent_code'   => 'AS',
				'currency_code'    => 'MNT',
				'int_calling_code' => '976',
				'languages'        => 'mn,ru',
			],
			[
				'code'             => 'MO',
				'name'             => 'Ngoumún',
				'tld'              => '.mo',
				'continent_code'   => 'AS',
				'currency_code'    => 'MOP',
				'int_calling_code' => '853',
				'languages'        => 'zh,zh-MO,pt',
			],
			[
				'code'             => 'MP',
				'name'             => 'Northern Mariana Islands',
				'tld'              => '.mp',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-670',
				'languages'        => 'fil,tl,zh,ch-MP,en-MP',
			],
			[
				'code'             => 'MQ',
				'name'             => 'Martinique',
				'tld'              => '.mq',
				'continent_code'   => 'NA',
				'currency_code'    => 'EUR',
				'int_calling_code' => '596',
				'languages'        => 'fr-MQ',
			],
			[
				'code'             => 'MR',
				'name'             => 'Mauritanie',
				'tld'              => '.mr',
				'continent_code'   => 'AF',
				'currency_code'    => 'MRO',
				'int_calling_code' => '222',
				'languages'        => 'ar-MR,fuc,snk,fr,mey,wo',
			],
			[
				'code'             => 'MS',
				'name'             => 'Montserrat',
				'tld'              => '.ms',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-664',
				'languages'        => 'en-MS',
			],
			[
				'code'             => 'MT',
				'name'             => 'Malta',
				'tld'              => '.mt',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '356',
				'languages'        => 'mt,en-MT',
			],
			[
				'code'             => 'MU',
				'name'             => 'Mauritius',
				'tld'              => '.mu',
				'continent_code'   => 'AF',
				'currency_code'    => 'MUR',
				'int_calling_code' => '230',
				'languages'        => 'en-MU,bho,fr',
			],
			[
				'code'             => 'MV',
				'name'             => 'Dhivehi',
				'tld'              => '.mv',
				'continent_code'   => 'AS',
				'currency_code'    => 'MVR',
				'int_calling_code' => '960',
				'languages'        => 'dv,en',
			],
			[
				'code'             => 'MW',
				'name'             => 'Malawi',
				'tld'              => '.mw',
				'continent_code'   => 'AF',
				'currency_code'    => 'MWK',
				'int_calling_code' => '265',
				'languages'        => 'ny,yao,tum,swk',
			],
			[
				'code'             => 'MX',
				'name'             => 'México',
				'tld'              => '.mx',
				'continent_code'   => 'NA',
				'currency_code'    => 'MXN',
				'int_calling_code' => '52',
				'languages'        => 'es-MX',
			],
			[
				'code'             => 'MY',
				'name'             => 'Malaysia',
				'tld'              => '.my',
				'continent_code'   => 'AS',
				'currency_code'    => 'MYR',
				'int_calling_code' => '60',
				'languages'        => 'ms-MY,en,zh,ta,te,ml,pa,th',
			],
			[
				'code'             => 'MZ',
				'name'             => 'Moçambique',
				'tld'              => '.mz',
				'continent_code'   => 'AF',
				'currency_code'    => 'MZN',
				'int_calling_code' => '258',
				'languages'        => 'pt-MZ,vmw',
			],
			[
				'code'             => 'NA',
				'name'             => 'Namibia',
				'tld'              => '.na',
				'continent_code'   => 'AF',
				'currency_code'    => 'NAD',
				'int_calling_code' => '264',
				'languages'        => 'en-NA,af,de,hz,naq',
			],
			[
				'code'             => 'NC',
				'name'             => 'Nouvelle Calédonie',
				'tld'              => '.nc',
				'continent_code'   => 'OC',
				'currency_code'    => 'XPF',
				'int_calling_code' => '687',
				'languages'        => 'fr-NC',
			],
			[
				'code'             => 'NE',
				'name'             => 'Niger',
				'tld'              => '.ne',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '227',
				'languages'        => 'fr-NE,ha,kr,dje',
			],
			[
				'code'             => 'NF',
				'name'             => 'Norfolk Island',
				'tld'              => '.nf',
				'continent_code'   => 'OC',
				'currency_code'    => 'AUD',
				'int_calling_code' => '672',
				'languages'        => 'en-NF',
			],
			[
				'code'             => 'NG',
				'name'             => 'Nigeria',
				'tld'              => '.ng',
				'continent_code'   => 'AF',
				'currency_code'    => 'NGN',
				'int_calling_code' => '234',
				'languages'        => 'en-NG,ha,yo,ig,ff',
			],
			[
				'code'             => 'NI',
				'name'             => 'Nicaragua',
				'tld'              => '.ni',
				'continent_code'   => 'NA',
				'currency_code'    => 'NIO',
				'int_calling_code' => '505',
				'languages'        => 'es-NI,en',
			],
			[
				'code'             => 'NL',
				'name'             => 'Nederland',
				'tld'              => '.nl',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '31',
				'languages'        => 'nl-NL,fy-NL',
			],
			[
				'code'             => 'NO',
				'name'             => 'Norge (Noreg)',
				'tld'              => '.no',
				'continent_code'   => 'EU',
				'currency_code'    => 'NOK',
				'int_calling_code' => '47',
				'languages'        => 'no,nb,nn,se,fi',
			],
			[
				'code'             => 'NP',
				'name'             => 'Nēpāl',
				'tld'              => '.np',
				'continent_code'   => 'AS',
				'currency_code'    => 'NPR',
				'int_calling_code' => '977',
				'languages'        => 'ne,en',
			],
			[
				'code'             => 'NR',
				'name'             => 'Naoero',
				'tld'              => '.nr',
				'continent_code'   => 'OC',
				'currency_code'    => 'AUD',
				'int_calling_code' => '674',
				'languages'        => 'na,en-NR',
			],
			[
				'code'             => 'NU',
				'name'             => 'Niue',
				'tld'              => '.nu',
				'continent_code'   => 'OC',
				'currency_code'    => 'NZD',
				'int_calling_code' => '683',
				'languages'        => 'niu,en-NU',
			],
			[
				'code'             => 'NZ',
				'name'             => 'New Zealand',
				'tld'              => '.nz',
				'continent_code'   => 'OC',
				'currency_code'    => 'NZD',
				'int_calling_code' => '64',
				'languages'        => 'en-NZ,mi',
			],
			[
				'code'             => 'OM',
				'name'             => 'ʿUmān',
				'tld'              => '.om',
				'continent_code'   => 'AS',
				'currency_code'    => 'OMR',
				'int_calling_code' => '968',
				'languages'        => 'ar-OM,en,bal,ur',
			],
			[
				'code'             => 'PA',
				'name'             => 'Panamá',
				'tld'              => '.pa',
				'continent_code'   => 'NA',
				'currency_code'    => 'PAB',
				'int_calling_code' => '507',
				'languages'        => 'es-PA,en',
			],
			[
				'code'             => 'PE',
				'name'             => 'Perú',
				'tld'              => '.pe',
				'continent_code'   => 'SA',
				'currency_code'    => 'PEN',
				'int_calling_code' => '51',
				'languages'        => 'es-PE,qu,ay',
			],
			[
				'code'             => 'PF',
				'name'             => 'Polinésie Française',
				'tld'              => '.pf',
				'continent_code'   => 'OC',
				'currency_code'    => 'XPF',
				'int_calling_code' => '689',
				'languages'        => 'fr-PF,ty',
			],
			[
				'code'             => 'PG',
				'name'             => 'Papua New Guinea',
				'tld'              => '.pg',
				'continent_code'   => 'OC',
				'currency_code'    => 'PGK',
				'int_calling_code' => '675',
				'languages'        => 'en-PG,ho,meu,tpi',
			],
			[
				'code'             => 'PH',
				'name'             => 'Pilipinas',
				'tld'              => '.ph',
				'continent_code'   => 'AS',
				'currency_code'    => 'PHP',
				'int_calling_code' => '63',
				'languages'        => 'tl,en-PH,fil',
			],
			[
				'code'             => 'PK',
				'name'             => 'Pākistān',
				'tld'              => '.pk',
				'continent_code'   => 'AS',
				'currency_code'    => 'PKR',
				'int_calling_code' => '92',
				'languages'        => 'ur-PK,en-PK,pa,sd,ps,brh',
			],
			[
				'code'             => 'PL',
				'name'             => 'Polska',
				'tld'              => '.pl',
				'continent_code'   => 'EU',
				'currency_code'    => 'PLN',
				'int_calling_code' => '48',
				'languages'        => 'pl',
			],
			[
				'code'             => 'PM',
				'name'             => 'Saint Pierre and Miquelon',
				'tld'              => '.pm',
				'continent_code'   => 'NA',
				'currency_code'    => 'EUR',
				'int_calling_code' => '508',
				'languages'        => 'fr-PM',
			],
			[
				'code'             => 'PN',
				'name'             => 'Pitcairn',
				'tld'              => '.pn',
				'continent_code'   => 'OC',
				'currency_code'    => 'NZD',
				'int_calling_code' => '870',
				'languages'        => 'en-PN',
			],
			[
				'code'             => 'PR',
				'name'             => 'Puerto Rico',
				'tld'              => '.pr',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-787/1-939',
				'languages'        => 'en-PR,es-PR',
			],
			[
				'code'             => 'PS',
				'name'             => 'Filasṭīn',
				'tld'              => '.ps',
				'continent_code'   => 'AS',
				'currency_code'    => 'ILS',
				'int_calling_code' => '970',
				'languages'        => 'ar-PS',
			],
			[
				'code'             => 'PT',
				'name'             => 'Portugal',
				'tld'              => '.pt',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '351',
				'languages'        => 'pt-PT,mwl',
			],
			[
				'code'             => 'PW',
				'name'             => 'Palau',
				'tld'              => '.pw',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '680',
				'languages'        => 'pau,sov,en-PW,tox,ja,fil,zh',
			],
			[
				'code'             => 'PY',
				'name'             => 'Paraguay',
				'tld'              => '.py',
				'continent_code'   => 'SA',
				'currency_code'    => 'PYG',
				'int_calling_code' => '595',
				'languages'        => 'es-PY,gn',
			],
			[
				'code'             => 'QA',
				'name'             => 'Qaṭar',
				'tld'              => '.qa',
				'continent_code'   => 'AS',
				'currency_code'    => 'QAR',
				'int_calling_code' => '974',
				'languages'        => 'ar-QA,en',
			],
			[
				'code'             => 'RE',
				'name'             => 'Réunion',
				'tld'              => '.re',
				'continent_code'   => 'AF',
				'currency_code'    => 'EUR',
				'int_calling_code' => '262',
				'languages'        => 'fr-RE',
			],
			[
				'code'             => 'RO',
				'name'             => 'România',
				'tld'              => '.ro',
				'continent_code'   => 'EU',
				'currency_code'    => 'RON',
				'int_calling_code' => '40',
				'languages'        => 'ro,hu,rom',
			],
			[
				'code'             => 'RS',
				'name'             => 'Srbija',
				'tld'              => '.rs',
				'continent_code'   => 'EU',
				'currency_code'    => 'RSD',
				'int_calling_code' => '381',
				'languages'        => 'sr,hu,bs,rom',
			],
			[
				'code'             => 'RU',
				'name'             => 'Rossija',
				'tld'              => '.ru',
				'continent_code'   => 'EU',
				'currency_code'    => 'RUB',
				'int_calling_code' => '7',
				'languages'        => 'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv',
			],
			[
				'code'             => 'RW',
				'name'             => 'Rwanda',
				'tld'              => '.rw',
				'continent_code'   => 'AF',
				'currency_code'    => 'RWF',
				'int_calling_code' => '250',
				'languages'        => 'rw,en-RW,fr-RW,sw',
			],
			[
				'code'             => 'SA',
				'name'             => 'as-Saʿūdīyâ',
				'tld'              => '.sa',
				'continent_code'   => 'AS',
				'currency_code'    => 'SAR',
				'int_calling_code' => '966',
				'languages'        => 'ar-SA',
			],
			[
				'code'             => 'SB',
				'name'             => 'Solomon Islands',
				'tld'              => '.sb',
				'continent_code'   => 'OC',
				'currency_code'    => 'SBD',
				'int_calling_code' => '677',
				'languages'        => 'en-SB,tpi',
			],
			[
				'code'             => 'SC',
				'name'             => 'Seychelles',
				'tld'              => '.sc',
				'continent_code'   => 'AF',
				'currency_code'    => 'SCR',
				'int_calling_code' => '248',
				'languages'        => 'en-SC,fr-SC',
			],
			[
				'code'             => 'SD',
				'name'             => 'Sudan',
				'tld'              => '.sd',
				'continent_code'   => 'AF',
				'currency_code'    => 'SDG',
				'int_calling_code' => '249',
				'languages'        => 'ar-SD,en,fia',
			],
			[
				'code'             => 'SE',
				'name'             => 'Sverige',
				'tld'              => '.se',
				'continent_code'   => 'EU',
				'currency_code'    => 'SEK',
				'int_calling_code' => '46',
				'languages'        => 'sv-SE,se,sma,fi-SE',
			],
			[
				'code'             => 'SG',
				'name'             => 'xīnjiāpō',
				'tld'              => '.sg',
				'continent_code'   => 'AS',
				'currency_code'    => 'SGD',
				'int_calling_code' => '65',
				'languages'        => 'cmn,en-SG,ms-SG,ta-SG,zh-SG',
			],
			[
				'code'             => 'SH',
				'name'             => 'Saint Helena',
				'tld'              => '.sh',
				'continent_code'   => 'AF',
				'currency_code'    => 'SHP',
				'int_calling_code' => '290',
				'languages'        => 'en-SH',
			],
			[
				'code'             => 'SI',
				'name'             => 'Slovenija',
				'tld'              => '.si',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '386',
				'languages'        => 'sl,sh',
			],
			[
				'code'             => 'SJ',
				'name'             => 'Svalbard and Jan Mayen',
				'tld'              => '.sj',
				'continent_code'   => 'EU',
				'currency_code'    => 'NOK',
				'int_calling_code' => '47',
				'languages'        => 'no,ru',
			],
			[
				'code'             => 'SK',
				'name'             => 'Slovensko',
				'tld'              => '.sk',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '421',
				'languages'        => 'sk,hu',
			],
			[
				'code'             => 'SL',
				'name'             => 'Sierra Leone',
				'tld'              => '.sl',
				'continent_code'   => 'AF',
				'currency_code'    => 'SLL',
				'int_calling_code' => '232',
				'languages'        => 'en-SL,men,tem',
			],
			[
				'code'             => 'SM',
				'name'             => 'San Marino',
				'tld'              => '.sm',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '378',
				'languages'        => 'it-SM',
			],
			[
				'code'             => 'SN',
				'name'             => 'Sénégal',
				'tld'              => '.sn',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '221',
				'languages'        => 'fr-SN,wo,fuc,mnk',
			],
			[
				'code'             => 'SO',
				'name'             => 'Soomaaliya',
				'tld'              => '.so',
				'continent_code'   => 'AF',
				'currency_code'    => 'SOS',
				'int_calling_code' => '252',
				'languages'        => 'so-SO,ar-SO,it,en-SO',
			],
			[
				'code'             => 'SR',
				'name'             => 'Suriname',
				'tld'              => '.sr',
				'continent_code'   => 'SA',
				'currency_code'    => 'SRD',
				'int_calling_code' => '597',
				'languages'        => 'nl-SR,en,srn,hns,jv',
			],
			[
				'code'             => 'SS',
				'name'             => 'South Sudan',
				'tld'              => '',
				'continent_code'   => 'AF',
				'currency_code'    => 'SSP',
				'int_calling_code' => '211',
				'languages'        => 'en',
			],
			[
				'code'             => 'ST',
				'name'             => 'São Tomé e Príncipe',
				'tld'              => '.st',
				'continent_code'   => 'AF',
				'currency_code'    => 'STD',
				'int_calling_code' => '239',
				'languages'        => 'pt-ST',
			],
			[
				'code'             => 'SV',
				'name'             => 'El Salvador',
				'tld'              => '.sv',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '503',
				'languages'        => 'es-SV',
			],
			[
				'code'             => 'SX',
				'name'             => 'Sint Maarten',
				'tld'              => '.sx',
				'continent_code'   => 'NA',
				'currency_code'    => 'ANG',
				'int_calling_code' => '599',
				'languages'        => 'nl,en',
			],
			[
				'code'             => 'SY',
				'name'             => 'Sūrīyâ',
				'tld'              => '.sy',
				'continent_code'   => 'AS',
				'currency_code'    => 'SYP',
				'int_calling_code' => '963',
				'languages'        => 'ar-SY,ku,hy,arc,fr,en',
			],
			[
				'code'             => 'SZ',
				'name'             => 'Swaziland',
				'tld'              => '.sz',
				'continent_code'   => 'AF',
				'currency_code'    => 'SZL',
				'int_calling_code' => '268',
				'languages'        => 'en-SZ,ss-SZ',
			],
			[
				'code'             => 'TC',
				'name'             => 'Turks and Caicos Islands',
				'tld'              => '.tc',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-649',
				'languages'        => 'en-TC',
			],
			[
				'code'             => 'TD',
				'name'             => 'Tchad',
				'tld'              => '.td',
				'continent_code'   => 'AF',
				'currency_code'    => 'XAF',
				'int_calling_code' => '235',
				'languages'        => 'fr-TD,ar-TD,sre',
			],
			[
				'code'             => 'TF',
				'name'             => 'French Southern Territories',
				'tld'              => '.tf',
				'continent_code'   => 'AN',
				'currency_code'    => 'EUR',
				'int_calling_code' => '',
				'languages'        => 'fr',
			],
			[
				'code'             => 'TG',
				'name'             => 'Togo',
				'tld'              => '.tg',
				'continent_code'   => 'AF',
				'currency_code'    => 'XOF',
				'int_calling_code' => '228',
				'languages'        => 'fr-TG,ee,hna,kbp,dag,ha',
			],
			[
				'code'             => 'TH',
				'name'             => 'Prathēt tai',
				'tld'              => '.th',
				'continent_code'   => 'AS',
				'currency_code'    => 'THB',
				'int_calling_code' => '66',
				'languages'        => 'th,en',
			],
			[
				'code'             => 'TJ',
				'name'             => 'Tojikiston',
				'tld'              => '.tj',
				'continent_code'   => 'AS',
				'currency_code'    => 'TJS',
				'int_calling_code' => '992',
				'languages'        => 'tg,ru',
			],
			[
				'code'             => 'TK',
				'name'             => 'Tokelau',
				'tld'              => '.tk',
				'continent_code'   => 'OC',
				'currency_code'    => 'NZD',
				'int_calling_code' => '690',
				'languages'        => 'tkl,en-TK',
			],
			[
				'code'             => 'TL',
				'name'             => 'Timór Lorosa\'e',
				'tld'              => '.tl',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '670',
				'languages'        => 'tet,pt-TL,id,en',
			],
			[
				'code'             => 'TM',
				'name'             => 'Turkmenistan',
				'tld'              => '.tm',
				'continent_code'   => 'AS',
				'currency_code'    => 'TMT',
				'int_calling_code' => '993',
				'languages'        => 'tk,ru,uz',
			],
			[
				'code'             => 'TN',
				'name'             => 'Tunisie',
				'tld'              => '.tn',
				'continent_code'   => 'AF',
				'currency_code'    => 'TND',
				'int_calling_code' => '216',
				'languages'        => 'ar-TN,fr',
			],
			[
				'code'             => 'TO',
				'name'             => 'Tonga',
				'tld'              => '.to',
				'continent_code'   => 'OC',
				'currency_code'    => 'TOP',
				'int_calling_code' => '676',
				'languages'        => 'to,en-TO',
			],
			[
				'code'             => 'TR',
				'name'             => 'Türkiye',
				'tld'              => '.tr',
				'continent_code'   => 'AS',
				'currency_code'    => 'TRY',
				'int_calling_code' => '90',
				'languages'        => 'tr-TR,ku,diq,az,av',
			],
			[
				'code'             => 'TT',
				'name'             => 'Trinidad and Tobago',
				'tld'              => '.tt',
				'continent_code'   => 'NA',
				'currency_code'    => 'TTD',
				'int_calling_code' => '+1-868',
				'languages'        => 'en-TT,hns,fr,es,zh',
			],
			[
				'code'             => 'TV',
				'name'             => 'Tuvalu',
				'tld'              => '.tv',
				'continent_code'   => 'OC',
				'currency_code'    => 'AUD',
				'int_calling_code' => '688',
				'languages'        => 'tvl,en,sm,gil',
			],
			[
				'code'             => 'TW',
				'name'             => 'T\'ai2-wan1',
				'tld'              => '.tw',
				'continent_code'   => 'AS',
				'currency_code'    => 'TWD',
				'int_calling_code' => '886',
				'languages'        => 'zh-TW,zh,nan,hak',
			],
			[
				'code'             => 'TZ',
				'name'             => 'Tanzania',
				'tld'              => '.tz',
				'continent_code'   => 'AF',
				'currency_code'    => 'TZS',
				'int_calling_code' => '255',
				'languages'        => 'sw-TZ,en,ar',
			],
			[
				'code'             => 'UA',
				'name'             => 'Ukrajina',
				'tld'              => '.ua',
				'continent_code'   => 'EU',
				'currency_code'    => 'UAH',
				'int_calling_code' => '380',
				'languages'        => 'uk,ru-UA,rom,pl,hu',
			],
			[
				'code'             => 'UG',
				'name'             => 'Uganda',
				'tld'              => '.ug',
				'continent_code'   => 'AF',
				'currency_code'    => 'UGX',
				'int_calling_code' => '256',
				'languages'        => 'en-UG,lg,sw,ar',
			],
			[
				'code'             => 'UK',
				'name'             => 'United Kingdom',
				'tld'              => '.uk',
				'continent_code'   => 'EU',
				'currency_code'    => 'GBP',
				'int_calling_code' => '44',
				'languages'        => 'en-GB,cy-GB,gd',
			],
			[
				'code'             => 'UM',
				'name'             => 'United States Minor Outlying Islands',
				'tld'              => '.um',
				'continent_code'   => 'OC',
				'currency_code'    => 'USD',
				'int_calling_code' => '1',
				'languages'        => 'en-UM',
			],
			[
				'code'             => 'US',
				'name'             => 'USA',
				'tld'              => '.us',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '1',
				'languages'        => 'en-US,es-US,haw,fr',
			],
			[
				'code'             => 'UY',
				'name'             => 'Uruguay',
				'tld'              => '.uy',
				'continent_code'   => 'SA',
				'currency_code'    => 'UYU',
				'int_calling_code' => '598',
				'languages'        => 'es-UY',
			],
			[
				'code'             => 'UZ',
				'name'             => 'O\'zbekiston',
				'tld'              => '.uz',
				'continent_code'   => 'AS',
				'currency_code'    => 'UZS',
				'int_calling_code' => '998',
				'languages'        => 'uz,ru,tg',
			],
			[
				'code'             => 'VA',
				'name'             => 'Vaticanum',
				'tld'              => '.va',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '379',
				'languages'        => 'la,it,fr',
			],
			[
				'code'             => 'VC',
				'name'             => 'Saint Vincent and the Grenadines',
				'tld'              => '.vc',
				'continent_code'   => 'NA',
				'currency_code'    => 'XCD',
				'int_calling_code' => '+1-784',
				'languages'        => 'en-VC,fr',
			],
			[
				'code'             => 'VE',
				'name'             => 'Venezuela',
				'tld'              => '.ve',
				'continent_code'   => 'SA',
				'currency_code'    => 'VEF',
				'int_calling_code' => '58',
				'languages'        => 'es-VE',
			],
			[
				'code'             => 'VG',
				'name'             => 'British Virgin Islands',
				'tld'              => '.vg',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-284',
				'languages'        => 'en-VG',
			],
			[
				'code'             => 'VI',
				'name'             => 'U.S. Virgin Islands',
				'tld'              => '.vi',
				'continent_code'   => 'NA',
				'currency_code'    => 'USD',
				'int_calling_code' => '+1-340',
				'languages'        => 'en-VI',
			],
			[
				'code'             => 'VN',
				'name'             => 'Việt Nam',
				'tld'              => '.vn',
				'continent_code'   => 'AS',
				'currency_code'    => 'VND',
				'int_calling_code' => '84',
				'languages'        => 'vi,en,fr,zh,km',
			],
			[
				'code'             => 'VU',
				'name'             => 'Vanuatu',
				'tld'              => '.vu',
				'continent_code'   => 'OC',
				'currency_code'    => 'VUV',
				'int_calling_code' => '678',
				'languages'        => 'bi,en-VU,fr-VU',
			],
			[
				'code'             => 'WF',
				'name'             => 'Wallis and Futuna',
				'tld'              => '.wf',
				'continent_code'   => 'OC',
				'currency_code'    => 'XPF',
				'int_calling_code' => '681',
				'languages'        => 'wls,fud,fr-WF',
			],
			[
				'code'             => 'WS',
				'name'             => 'Samoa',
				'tld'              => '.ws',
				'continent_code'   => 'OC',
				'currency_code'    => 'WST',
				'int_calling_code' => '685',
				'languages'        => 'sm,en-WS',
			],
			[
				'code'             => 'XK',
				'name'             => 'Kosovo',
				'tld'              => '',
				'continent_code'   => 'EU',
				'currency_code'    => 'EUR',
				'int_calling_code' => '',
				'languages'        => 'sq,sr',
			],
			[
				'code'             => 'YE',
				'name'             => 'al-Yaman',
				'tld'              => '.ye',
				'continent_code'   => 'AS',
				'currency_code'    => 'YER',
				'int_calling_code' => '967',
				'languages'        => 'ar-YE',
			],
			[
				'code'             => 'YT',
				'name'             => 'Mayotte',
				'tld'              => '.yt',
				'continent_code'   => 'AF',
				'currency_code'    => 'EUR',
				'int_calling_code' => '262',
				'languages'        => 'fr-YT',
			],
			[
				'code'             => 'ZA',
				'name'             => 'South Africa',
				'tld'              => '.za',
				'continent_code'   => 'AF',
				'currency_code'    => 'ZAR',
				'int_calling_code' => '27',
				'languages'        => 'zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr',
			],
			[
				'code'             => 'ZM',
				'name'             => 'Zambia',
				'tld'              => '.zm',
				'continent_code'   => 'AF',
				'currency_code'    => 'ZMW',
				'int_calling_code' => '260',
				'languages'        => 'en-ZM,bem,loz,lun,lue,ny,toi',
			],
			[
				'code'             => 'ZW',
				'name'             => 'Zimbabwe',
				'tld'              => '.zw',
				'continent_code'   => 'AF',
				'currency_code'    => 'ZWL',
				'int_calling_code' => '263',
				'languages'        => 'en-ZW,sn,nr,nd',
			],
		];
		
		foreach ($countries as $country) {
			Country::create($country);
		}
	}
}
