<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::statement('SET FOREIGN_KEY_CHECKS=0;');
		DB::table('currencies')->truncate();
		$currencies = [
			[
				'code'               => 'AED',
				'name'               => 'United Arab Emirates Dirham',
				'html_entity'        => 'د.إ',
				'symbol'             => 'د.إ',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'AFN',
				'name'               => 'Afghanistan Afghani',
				'html_entity'        => 'Af',
				'symbol'             => 'Af',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ALL',
				'name'               => 'Albania Lek',
				'html_entity'        => 'Lek',
				'symbol'             => 'Lek',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'AMD',
				'name'               => 'Armenia Dram',
				'html_entity'        => '',
				'symbol'             => '',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ANG',
				'name'               => 'Netherlands Antilles Guilder',
				'html_entity'        => 'ƒ',
				'symbol'             => 'ƒ',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'AOA',
				'name'               => 'Angola Kwanza',
				'html_entity'        => 'Kz',
				'symbol'             => 'Kz',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ARS',
				'name'               => 'Argentina Peso',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'AUD',
				'name'               => 'Australia Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'AWG',
				'name'               => 'Aruba Guilder',
				'html_entity'        => 'ƒ',
				'symbol'             => 'ƒ',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'AZN',
				'name'               => 'Azerbaijan New Manat',
				'html_entity'        => 'ман',
				'symbol'             => 'ман',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BAM',
				'name'               => 'Bosnia and Herzegovina Convertible Marka',
				'html_entity'        => 'KM',
				'symbol'             => 'KM',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BBD',
				'name'               => 'Barbados Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BDT',
				'name'               => 'Bangladesh Taka',
				'html_entity'        => '৳',
				'symbol'             => '৳',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BGN',
				'name'               => 'Bulgaria Lev',
				'html_entity'        => 'лв',
				'symbol'             => 'лв',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BHD',
				'name'               => 'Bahrain Dinar',
				'html_entity'        => '.د.ب',
				'symbol'             => '.د.ب',
				'in_left'            => 0,
				'decimal_places'     => 3,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BIF',
				'name'               => 'Burundi Franc',
				'html_entity'        => 'FBu',
				'symbol'             => 'FBu',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BMD',
				'name'               => 'Bermuda Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BND',
				'name'               => 'Brunei Darussalam Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BOB',
				'name'               => 'Bolivia Boliviano',
				'html_entity'        => '$b',
				'symbol'             => '$b',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BRL',
				'name'               => 'Brazil Real',
				'html_entity'        => 'R$',
				'symbol'             => 'R$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BSD',
				'name'               => 'Bahamas Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BTN',
				'name'               => 'Bhutan Ngultrum',
				'html_entity'        => 'Nu.',
				'symbol'             => 'Nu.',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BWP',
				'name'               => 'Botswana Pula',
				'html_entity'        => 'P',
				'symbol'             => 'P',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BYR',
				'name'               => 'Belarus Ruble',
				'html_entity'        => 'p.',
				'symbol'             => 'p.',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'BZD',
				'name'               => 'Belize Dollar',
				'html_entity'        => 'BZ$',
				'symbol'             => 'BZ$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CAD',
				'name'               => 'Canada Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CDF',
				'name'               => 'Congo/Kinshasa Franc',
				'html_entity'        => 'FC',
				'symbol'             => 'FC',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CHF',
				'name'               => 'Switzerland Franc',
				'html_entity'        => '',
				'symbol'             => '',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CLP',
				'name'               => 'Chile Peso',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CNY',
				'name'               => 'China Yuan Renminbi',
				'html_entity'        => '¥',
				'symbol'             => '¥',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'COP',
				'name'               => 'Colombia Peso',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CRC',
				'name'               => 'Costa Rica Colon',
				'html_entity'        => '₡',
				'symbol'             => '₡',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CUC',
				'name'               => 'Cuba Convertible Peso',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CUP',
				'name'               => 'Cuba Peso',
				'html_entity'        => '⃌',
				'symbol'             => '⃌',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CVE',
				'name'               => 'Cape Verde Escudo',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'CZK',
				'name'               => 'Czech Republic Koruna',
				'html_entity'        => 'Kč',
				'symbol'             => 'Kč',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'DJF',
				'name'               => 'Djibouti Franc',
				'html_entity'        => 'Fdj',
				'symbol'             => 'Fdj',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'DKK',
				'name'               => 'Denmark Krone',
				'html_entity'        => 'kr',
				'symbol'             => 'kr',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'DOP',
				'name'               => 'Dominican Republic Peso',
				'html_entity'        => 'RD$',
				'symbol'             => 'RD$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'DZD',
				'name'               => 'Algeria Dinar',
				'html_entity'        => 'دج',
				'symbol'             => 'دج',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'EEK',
				'name'               => 'Estonia Kroon',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'EGP',
				'name'               => 'Egypt Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ERN',
				'name'               => 'Eritrea Nakfa',
				'html_entity'        => 'Nfk',
				'symbol'             => 'Nfk',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ETB',
				'name'               => 'Ethiopia Birr',
				'html_entity'        => 'Br',
				'symbol'             => 'Br',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'EUR',
				'name'               => 'Euro Member Countrys',
				'html_entity'        => '€',
				'symbol'             => '€',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => ',',
				'thousand_separator' => ' ',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'FJD',
				'name'               => 'Fiji Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'FKP',
				'name'               => 'Falkland Islands (Malvinas) Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GBP',
				'name'               => 'United Kingdom Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GEL',
				'name'               => 'Georgia Lari',
				'html_entity'        => 'ლ',
				'symbol'             => 'ლ',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GGP',
				'name'               => 'Guernsey Pound',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GHC',
				'name'               => 'Ghana Cedi',
				'html_entity'        => 'GH¢',
				'symbol'             => 'GH¢',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GHS',
				'name'               => 'Ghana Cedi',
				'html_entity'        => 'GH¢',
				'symbol'             => 'GH¢',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GIP',
				'name'               => 'Gibraltar Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GMD',
				'name'               => 'Gambia Dalasi',
				'html_entity'        => 'D',
				'symbol'             => 'D',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GNF',
				'name'               => 'Guinea Franc',
				'html_entity'        => 'FG',
				'symbol'             => 'FG',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GTQ',
				'name'               => 'Guatemala Quetzal',
				'html_entity'        => 'Q',
				'symbol'             => 'Q',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'GYD',
				'name'               => 'Guyana Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'HKD',
				'name'               => 'Hong Kong Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'HNL',
				'name'               => 'Honduras Lempira',
				'html_entity'        => 'L',
				'symbol'             => 'L',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'HRK',
				'name'               => 'Croatia Kuna',
				'html_entity'        => 'kn',
				'symbol'             => 'kn',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'HTG',
				'name'               => 'Haiti Gourde',
				'html_entity'        => 'G',
				'symbol'             => 'G',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'HUF',
				'name'               => 'Hungary Forint',
				'html_entity'        => 'Ft',
				'symbol'             => 'Ft',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'IDR',
				'name'               => 'Indonesia Rupiah',
				'html_entity'        => 'Rp',
				'symbol'             => 'Rp',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ILS',
				'name'               => 'Israel Shekel',
				'html_entity'        => '₪',
				'symbol'             => '₪',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'IMP',
				'name'               => 'Isle of Man Pound',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'INR',
				'name'               => 'India Rupee',
				'html_entity'        => '₹',
				'symbol'             => '₹',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'IQD',
				'name'               => 'Iraq Dinar',
				'html_entity'        => 'ع.د',
				'symbol'             => 'ع.د',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'IRR',
				'name'               => 'Iran Rial',
				'html_entity'        => '﷼',
				'symbol'             => '﷼',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ISK',
				'name'               => 'Iceland Krona',
				'html_entity'        => 'kr',
				'symbol'             => 'kr',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'JEP',
				'name'               => 'Jersey Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'JMD',
				'name'               => 'Jamaica Dollar',
				'html_entity'        => 'J$',
				'symbol'             => 'J$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'JOD',
				'name'               => 'Jordan Dinar',
				'html_entity'        => 'JD',
				'symbol'             => 'JD',
				'in_left'            => 0,
				'decimal_places'     => 3,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'JPY',
				'name'               => 'Japan Yen',
				'html_entity'        => '¥',
				'symbol'             => '¥',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KES',
				'name'               => 'Kenya Shilling',
				'html_entity'        => 'KSh',
				'symbol'             => 'KSh',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KGS',
				'name'               => 'Kyrgyzstan Som',
				'html_entity'        => 'лв',
				'symbol'             => 'лв',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KHR',
				'name'               => 'Cambodia Riel',
				'html_entity'        => '៛',
				'symbol'             => '៛',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KMF',
				'name'               => 'Comoros Franc',
				'html_entity'        => 'CF',
				'symbol'             => 'CF',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KPW',
				'name'               => 'Korea (North) Won',
				'html_entity'        => '₩',
				'symbol'             => '₩',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KRW',
				'name'               => 'Korea (South) Won',
				'html_entity'        => '₩',
				'symbol'             => '₩',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KWD',
				'name'               => 'Kuwait Dinar',
				'html_entity'        => 'د.ك',
				'symbol'             => 'د.ك',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KYD',
				'name'               => 'Cayman Islands Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'KZT',
				'name'               => 'Kazakhstan Tenge',
				'html_entity'        => 'лв',
				'symbol'             => 'лв',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LAK',
				'name'               => 'Laos Kip',
				'html_entity'        => '₭',
				'symbol'             => '₭',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LBP',
				'name'               => 'Lebanon Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LKR',
				'name'               => 'Sri Lanka Rupee',
				'html_entity'        => '₨',
				'symbol'             => '₨',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LRD',
				'name'               => 'Liberia Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LSL',
				'name'               => 'Lesotho Loti',
				'html_entity'        => 'L',
				'symbol'             => 'L',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LTL',
				'name'               => 'Lithuania Litas',
				'html_entity'        => 'Lt',
				'symbol'             => 'Lt',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LVL',
				'name'               => 'Latvia Lat',
				'html_entity'        => 'Ls',
				'symbol'             => 'Ls',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'LYD',
				'name'               => 'Libya Dinar',
				'html_entity'        => 'ل.د',
				'symbol'             => 'ل.د',
				'in_left'            => 0,
				'decimal_places'     => 3,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MAD',
				'name'               => 'Morocco Dirham',
				'html_entity'        => 'د.م.',
				'symbol'             => 'د.م.',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MDL',
				'name'               => 'Moldova Leu',
				'html_entity'        => 'L',
				'symbol'             => 'L',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MGA',
				'name'               => 'Madagascar Ariary',
				'html_entity'        => 'Ar',
				'symbol'             => 'Ar',
				'in_left'            => 0,
				'decimal_places'     => 5,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MKD',
				'name'               => 'Macedonia Denar',
				'html_entity'        => 'ден',
				'symbol'             => 'ден',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MMK',
				'name'               => 'Myanmar (Burma) Kyat',
				'html_entity'        => 'K',
				'symbol'             => 'K',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MNT',
				'name'               => 'Mongolia Tughrik',
				'html_entity'        => '₮',
				'symbol'             => '₮',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MOP',
				'name'               => 'Macau Pataca',
				'html_entity'        => 'MOP$',
				'symbol'             => 'MOP$',
				'in_left'            => 0,
				'decimal_places'     => 1,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MRO',
				'name'               => 'Mauritania Ouguiya',
				'html_entity'        => 'UM',
				'symbol'             => 'UM',
				'in_left'            => 0,
				'decimal_places'     => 5,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MUR',
				'name'               => 'Mauritius Rupee',
				'html_entity'        => '₨',
				'symbol'             => '₨',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MVR',
				'name'               => 'Maldives (Maldive Islands) Rufiyaa',
				'html_entity'        => '.ރ',
				'symbol'             => '.ރ',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MWK',
				'name'               => 'Malawi Kwacha',
				'html_entity'        => 'MK',
				'symbol'             => 'MK',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MXN',
				'name'               => 'Mexico Peso',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MYR',
				'name'               => 'Malaysia Ringgit',
				'html_entity'        => 'RM',
				'symbol'             => 'RM',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'MZN',
				'name'               => 'Mozambique Metical',
				'html_entity'        => 'MT',
				'symbol'             => 'MT',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'NAD',
				'name'               => 'Namibia Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'NGN',
				'name'               => 'Nigeria Naira',
				'html_entity'        => '₦',
				'symbol'             => '₦',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'NIO',
				'name'               => 'Nicaragua Cordoba',
				'html_entity'        => 'C$',
				'symbol'             => 'C$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'NOK',
				'name'               => 'Norway Krone',
				'html_entity'        => 'kr',
				'symbol'             => 'kr',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'NPR',
				'name'               => 'Nepal Rupee',
				'html_entity'        => '₨',
				'symbol'             => '₨',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'NZD',
				'name'               => 'New Zealand Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'OMR',
				'name'               => 'Oman Rial',
				'html_entity'        => '﷼',
				'symbol'             => '﷼',
				'in_left'            => 0,
				'decimal_places'     => 3,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PAB',
				'name'               => 'Panama Balboa',
				'html_entity'        => 'B/.',
				'symbol'             => 'B/.',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PEN',
				'name'               => 'Peru Nuevo Sol',
				'html_entity'        => 'S/.',
				'symbol'             => 'S/.',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PGK',
				'name'               => 'Papua New Guinea Kina',
				'html_entity'        => 'K',
				'symbol'             => 'K',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PHP',
				'name'               => 'Philippines Peso',
				'html_entity'        => '₱',
				'symbol'             => '₱',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PKR',
				'name'               => 'Pakistan Rupee',
				'html_entity'        => '₨',
				'symbol'             => '₨',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PLN',
				'name'               => 'Poland Zloty',
				'html_entity'        => 'zł',
				'symbol'             => 'zł',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'PYG',
				'name'               => 'Paraguay Guarani',
				'html_entity'        => 'Gs',
				'symbol'             => 'Gs',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'QAR',
				'name'               => 'Qatar Riyal',
				'html_entity'        => '﷼',
				'symbol'             => '﷼',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'RON',
				'name'               => 'Romania New Leu',
				'html_entity'        => 'lei',
				'symbol'             => 'lei',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'RSD',
				'name'               => 'Serbia Dinar',
				'html_entity'        => 'Дин.',
				'symbol'             => 'Дин.',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'RUB',
				'name'               => 'Russia Ruble',
				'html_entity'        => '₽',
				'symbol'             => '₽',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'RWF',
				'name'               => 'Rwanda Franc',
				'html_entity'        => 'ر.س',
				'symbol'             => 'ر.س',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SAR',
				'name'               => 'Saudi Arabia Riyal',
				'html_entity'        => '﷼',
				'symbol'             => '﷼',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SBD',
				'name'               => 'Solomon Islands Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SCR',
				'name'               => 'Seychelles Rupee',
				'html_entity'        => '₨',
				'symbol'             => '₨',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SDG',
				'name'               => 'Sudan Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SEK',
				'name'               => 'Sweden Krona',
				'html_entity'        => 'kr',
				'symbol'             => 'kr',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SGD',
				'name'               => 'Singapore Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SHP',
				'name'               => 'Saint Helena Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SLL',
				'name'               => 'Sierra Leone Leone',
				'html_entity'        => 'Le',
				'symbol'             => 'Le',
				'in_left'            => 1,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SOS',
				'name'               => 'Somalia Shilling',
				'html_entity'        => 'S',
				'symbol'             => 'S',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SPL',
				'name'               => 'Seborga Luigino',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SRD',
				'name'               => 'Suriname Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SSP',
				'name'               => 'South Sudanese Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'STD',
				'name'               => 'São Tomé and Príncipe Dobra',
				'html_entity'        => 'Db',
				'symbol'             => 'Db',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SVC',
				'name'               => 'El Salvador Colon',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SYP',
				'name'               => 'Syria Pound',
				'html_entity'        => '£',
				'symbol'             => '£',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'SZL',
				'name'               => 'Swaziland Lilangeni',
				'html_entity'        => 'L',
				'symbol'             => 'L',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'THB',
				'name'               => 'Thailand Baht',
				'html_entity'        => '฿',
				'symbol'             => '฿',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TJS',
				'name'               => 'Tajikistan Somoni',
				'html_entity'        => 'TJS',
				'symbol'             => 'TJS',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TMT',
				'name'               => 'Turkmenistan Manat',
				'html_entity'        => 'm',
				'symbol'             => 'm',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TND',
				'name'               => 'Tunisia Dinar',
				'html_entity'        => 'د.ت',
				'symbol'             => 'د.ت',
				'in_left'            => 1,
				'decimal_places'     => 3,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TOP',
				'name'               => 'Tonga Pa\'anga',
				'html_entity'        => 'T$',
				'symbol'             => 'T$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TRL',
				'name'               => 'Turkey Lira',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TRY',
				'name'               => 'Turkey Lira',
				'html_entity'        => '₺',
				'symbol'             => '₺',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TTD',
				'name'               => 'Trinidad and Tobago Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TVD',
				'name'               => 'Tuvalu Dollar',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TWD',
				'name'               => 'Taiwan New Dollar',
				'html_entity'        => 'NT$',
				'symbol'             => 'NT$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'TZS',
				'name'               => 'Tanzania Shilling',
				'html_entity'        => 'TSh',
				'symbol'             => 'TSh',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'UAH',
				'name'               => 'Ukraine Hryvnia',
				'html_entity'        => '₴',
				'symbol'             => '₴',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'UGX',
				'name'               => 'Uganda Shilling',
				'html_entity'        => 'USh',
				'symbol'             => 'USh',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'USD',
				'name'               => 'United States Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'UYU',
				'name'               => 'Uruguay Peso',
				'html_entity'        => '$U',
				'symbol'             => '$U',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'UZS',
				'name'               => 'Uzbekistan Som',
				'html_entity'        => 'лв',
				'symbol'             => 'лв',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'VEF',
				'name'               => 'Venezuela Bolivar',
				'html_entity'        => 'Bs',
				'symbol'             => 'Bs',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'VND',
				'name'               => 'Viet Nam Dong',
				'html_entity'        => '₫',
				'symbol'             => '₫',
				'in_left'            => 1,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'VUV',
				'name'               => 'Vanuatu Vatu',
				'html_entity'        => 'VT',
				'symbol'             => 'VT',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'WST',
				'name'               => 'Samoa Tala',
				'html_entity'        => 'WS$',
				'symbol'             => 'WS$',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'XAF',
				'name'               => 'Communauté Financière Africaine (BEAC) CFA Franc B',
				'html_entity'        => 'FCFA',
				'symbol'             => 'FCFA',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'XCD',
				'name'               => 'East Caribbean Dollar',
				'html_entity'        => '$',
				'symbol'             => '$',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'XDR',
				'name'               => 'International Monetary Fund (IMF) Special Drawing ',
				'html_entity'        => '',
				'symbol'             => '',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'XOF',
				'name'               => 'Communauté Financière Africaine (BCEAO) Franc',
				'html_entity'        => 'FCFA',
				'symbol'             => 'FCFA',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'XPF',
				'name'               => 'Comptoirs Français du Pacifique (CFP) Franc',
				'html_entity'        => 'F',
				'symbol'             => 'F',
				'in_left'            => 0,
				'decimal_places'     => 0,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'YER',
				'name'               => 'Yemen Rial',
				'html_entity'        => '﷼',
				'symbol'             => '﷼',
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ZAR',
				'name'               => 'South Africa Rand',
				'html_entity'        => 'R',
				'symbol'             => 'R',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ZMW',
				'name'               => 'Zambia Kwacha',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 0,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ZWD',
				'name'               => 'Zimbabwe Dollar',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'ZWL',
				'name'               => 'Zimbabwe Dollar',
				'html_entity'        => null,
				'symbol'             => null,
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
			[
				'code'               => 'XBT',
				'name'               => 'Bitcoin',
				'html_entity'        => '฿',
				'symbol'             => '฿',
				'in_left'            => 1,
				'decimal_places'     => 2,
				'decimal_separator'  => '.',
				'thousand_separator' => ',',
				'created_at'         => null,
				'updated_at'         => null,
			],
		];
		
		foreach ($currencies as $currency) {
			Currency::create($currency);
		}
	}
}
